### ISSUE TITLE
Highlight doesn't show which mode it's in

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/sponge-docs-theme#6]
I think some Issues currently located in /Spongedocs should belong here as they're design-related. This issue is derived from /SpongeDocs (see: SpongePowered/SpongeDocs#178 )

original Post by @kenzierocks:
I'd prefer it if the highlight button actually toggled (or something visual aid thing) when pressed, instead of just remaining the same. It would show the current state much better than having to find a code snippet + scroll to top + hit button.

**Comment by Minecrell** [comment]
Fixed with new theme, current code theme is marked as bold text.
